#!/usr/bin/env python3
"""Daily Briefing - Generate daily summary for Dashboard."""

import os
import json
import logging
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, List

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class DailyBriefing:
    """Generates daily briefing."""

    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.done = self.vault_path / 'Done'
        self.briefings = self.vault_path / 'Briefings'
        self.logs = self.vault_path / 'Logs'
        self.dashboard = self.vault_path / 'Dashboard.md'

        self.briefings.mkdir(parents=True, exist_ok=True)

        logger.info(f"DailyBriefing initialized")

    def count_items(self, folder: Path, pattern: str = '*.md') -> int:
        """Count items in folder."""
        if not folder.exists():
            return 0
        return len(list(folder.glob(pattern)))

    def get_today_stats(self) -> Dict:
        """Get today's statistics."""
        today = datetime.now().date()

        stats = {
            'emails_processed': 0,
            'whatsapp_messages': 0,
            'tasks_completed': 0,
            'revenue': 0.0
        }

        # Count done items from today
        if self.done.exists():
            for file_path in self.done.glob('*.md'):
                try:
                    mtime = datetime.fromtimestamp(file_path.stat().st_mtime).date()
                    if mtime == today:
                        name_lower = file_path.name.lower()
                        if 'email' in name_lower:
                            stats['emails_processed'] += 1
                        elif 'whatsapp' in name_lower:
                            stats['whatsapp_messages'] += 1
                        else:
                            stats['tasks_completed'] += 1
                except Exception as e:
                    logger.error(f"Error processing {file_path}: {e}")

        return stats

    def generate_briefing(self) -> str:
        """Generate briefing content."""
        stats = self.get_today_stats()
        today = datetime.now().strftime('%Y-%m-%d')

        # Count current queue
        needs_action = self.count_items(self.vault_path / 'Needs_Action')
        in_progress = self.count_items(self.vault_path / 'In_Progress')
        pending_approval = self.count_items(self.vault_path / 'Pending_Approval')

        content = f"""---
type: daily_briefing
date: "{today}"
generated: "{datetime.now().isoformat()}"
---

# Daily Briefing - {today}

## Good Morning! ☀️

Here's your daily summary from your AI Employee.

## Today's Activity

| Metric | Count |
|--------|-------|
| Emails Processed | {stats['emails_processed']} |
| WhatsApp Messages | {stats['whatsapp_messages']} |
| Tasks Completed | {stats['tasks_completed']} |
| Revenue | ${stats['revenue']:.2f} |

## Current Queue

| Queue | Count |
|-------|-------|
| Needs Action | {needs_action} |
| In Progress | {in_progress} |
| Pending Approval | {pending_approval} |

## Priority Items

### Urgent (Requires Attention)
_No urgent items detected_

### Today's Schedule
- [ ] Review Needs_Action folder
- [ ] Check Pending_Approval items
- [ ] Process In_Progress tasks

## Quick Actions

1. **Review urgent items** in [Needs_Action](./Needs_Action)
2. **Approve pending items** in [Pending_Approval](./Pending_Approval)
3. **Check completed tasks** in [Done](./Done)

## System Status

All systems operational. Watchers running normally.

---
*Generated by AI Employee at {datetime.now().strftime('%H:%M:%S')}*
*Next briefing: Tomorrow at 08:00*
"""

        return content

    def update_dashboard(self, briefing_content: str):
        """Update Dashboard.md with latest briefing."""
        try:
            if self.dashboard.exists():
                dashboard = self.dashboard.read_text(encoding='utf-8')

                # Update today's summary section
                # This is a simple replacement - in practice, you'd parse and update
                today = datetime.now().strftime('%Y-%m-%d')

                # Find and replace the Today's Summary section
                if '## Current Queue' in dashboard:
                    # Simple update approach
                    lines = dashboard.split('\n')
                    new_lines = []
                    in_summary = False

                    for line in lines:
                        if '## Current Queue' in line:
                            in_summary = True
                        elif line.startswith('## ') and in_summary:
                            in_summary = False

                        if in_summary and '### Needs Action' in line:
                            # Update counts here
                            pass

                        new_lines.append(line)

                    self.dashboard.write_text('\n'.join(new_lines), encoding='utf-8')
                    logger.info("Dashboard updated")

        except Exception as e:
            logger.error(f"Error updating dashboard: {e}")

    def save_briefing(self, content: str) -> Path:
        """Save briefing to file."""
        today = datetime.now().strftime('%Y-%m-%d')
        filename = f"BRIEFING_{today}.md"
        filepath = self.briefings / filename

        filepath.write_text(content, encoding='utf-8')
        logger.info(f"Saved briefing: {filepath}")
        return filepath

    def run(self):
        """Generate and save briefing."""
        logger.info("Generating daily briefing...")

        content = self.generate_briefing()
        filepath = self.save_briefing(content)
        self.update_dashboard(content)

        print(f"Briefing generated: {filepath}")


def main():
    """Main entry point."""
    import argparse

    parser = argparse.ArgumentParser(description='Daily Briefing Generator')
    parser.add_argument('--vault-path', required=True, help='Path to vault')

    args = parser.parse_args()

    briefing = DailyBriefing(vault_path=args.vault_path)
    briefing.run()


if __name__ == '__main__':
    main()
